### PR TITLE
Add standalone MD5 implementation to remove openssl dependency. Close…

### PR DESCRIPTION
**Pull request by msharov**

### CODE REVIEW

**Comment by kouya** [comment]
Yay, I'll merge and give it a try!

**Comment by msharov** [comment]
Not that I'm complaining, but it is supposed to work the other way around: give it a try and then merge :)

**Comment by kouya** [comment]
That's kinda what I meant. :p Though I cannot try on 32bit. The last md5 I had, had some funny issues with 32/64. That's why I originally used openssl's.

**Comment by msharov** [comment]
32bit issues are usually due to use of long to store 32bit values, a habit we perhaps picked up while writing 16bit code for DOS. This MD5 implementation uses uint32_t for all relevant types, preventing any word size issues.

**Comment by kouya** [comment]
And speaking of more contributing. Want to have write access to the repository? My time is limited atm and feels already bad that things take forever on my end. If you want to organize things a bit, feel free to do so.

**Comment by msharov** [comment]
I don't think that's necessary. I already made pretty much all the changes I wanted for my daily use. It's time for somebody else to scratch their itch.

**Comment by kouya** [comment]
Heh, ok. I'll try to wrap up things this week(end) and tag a new release. Thanks for all your contributions. <3

**Pull request merged**
